<?php
namespace App\Services\PollingUnit\Isa;
	
	class Isa_South
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				// 'KWANAR ISA, PRI. SCH.',
				// 'KURAR MOTA, PRI. SCH.',
				// 'SHIYAR DANBALABE MAITANSU PRI. SCH.',
				// 'UNDER GAWO TREE NEAR BOREHOLE MAIGARKE (SHIYAR DAN BALARABE MAI GARKE)',
				// 'SARDAUNA PRI SCH. (SHIYAR BALARABE YAR MAKAFI)',
				// 'SHIYAR DANBALARABE, SARDAUNA PRI. SCH.',
				// 'UNDER NEEM TREE YAR KASUWA MAGAJI (SHIYAR GAJO YAKASUWA MAGAJI)',
				// 'FILIN RIJIYA KUDA ALLAH (SH/GAJO KUDA ALLAH G/A SUK SEC)',
				// 'BAKIN TITI (GIDAN SEC.ILYASU)',
				// 'DAN MALIKI PRI SCH. (GARKAR SAKATARE ISA,KUSADA GIDAN SAKATARE)',
				// 'SHALLAMAWA , SHALLAMAWA',
				// 'BAKIN TITI HERAMA (HEREMA GIDAN ALHAJI JIJJI)',
				// 'BAKIN TITI (YAR KASUWA GIDAN TUDU SHOP)',
				// 'FILIN RIJIYA BOREHOLE DUDAKIN (SHIYAR MUHAMMAD DUDAKE)',
				// 'GARIN HASSAN',
				// 'SHIYAR D/B MAITANBU P/SCHOOL'

				['KWANAR ISA, PRI. SCH.', 431],
				['KURAR MOTA, PRI. SCH.', 744],
				['SHIYAR DANBALABE MAITANSU PRI. SCH.', 598],
				['SHIYAR DANBALABE, MAIGARKE', 511],
				['SHIYAR DANBALARABE, YAR MAKAFI', 863],
				['SHIYAR DANBALARABE, SARDAUNA PRI. SCH.', 1,175],
				['SHIYAR GAJO, YAKASUWAR MAGAJI', 908],
				['SH/GAJO KUDA ALLAH G/A SUK SEC', 924],
				['GIDAN SEC.ILYASU', 1,341],
				['GARKAR SAKATAREN ISA, KUSAGA GIDAN SAKATARE', 1097],
				['SHALLAMAWA , SHALLAMAWA', 530],
				['HERAMA GIDAN ALHAJI JIJJI', 955],
				['YARKASUWA, GIDAN TUDU SHOP', 560],
				['SHIYAR MUHAMMADU, DUDAKIN', 986],
				['GARIN HASSAN', 420],
				['SHIYAR D/B MAITANBU P/SCHOOL', 1,057]

			];
		}
	}