<?php
namespace App\Services\PollingUnit\Gwadabawa;
	
	class AsaraArewa
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				['SHIYAR HAKIMI, FADAN KAI',386],
				['GARI, MAMMAN SUKA',663],
				['PRIMARY SCHOOL GIDAN ANAZAR (TSAKAR GARI GIDAN ANAZAR)',439],
				['UNDER THREE SHADE, ZANGO NAHANTSI OPEN SPACE (TSAKAR GARI ZANGO N/HANTSI)',305],
				['PRIMARY SCHOOL, BAUDA (PRIMARY SCHOOL BAUDA)',478],
				['CENTRAL MOSQUE, BAKIN MASALACI, MAKINA ALFARMA OPEN SPACE (BAKIN MASALACI MAKINA ALFARMA)',459],
				['DISPENSARY MAKINA MAIFUCHI (TSAKAR GARI MAKINA M/FUCHI)',565],
				['PRIMARY SCHOOL HURA/MAGAMA (PRIMARY SCHOOL HURA HURA/MAGAMA)',649],
				['PRIMARY SCHOOL MUWAILA (PRY SCH. T. MUWAILA, TUDUN MUWAILA)',724],
				['SHIYAR HAKIMI, MAMAN SUKA GARI',740],
				['PRIMARY SCHOOL MAMMAN SUKA (PRI. SCH. M. SUKA G. GEZA)',705],
				['UNDER THREE SHADE, TSAKAR GARI OPEN SPACE (TSAKAR GARI MALLAMAWA KAGALABA.)',396],
				['DISPENSARY, FADAN KAI',399],
				['SHIYAR HAKIMI, MAKINA ALFARMA',397]
			];
		}
	}