<?php
namespace App\Services\PollingUnit\Gwadabawa;
	
	class AsaraKudu
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				['SHIYAR MAGAJI',716],
				['OPPOSITE HOSPITAL, OPEN SPACE (SHIYAR GALADIMA, SH GAL.)',740],
				['PRIMARY SCHOOL MAKARANTA, SHIYAR GALADIMA (MAKARANTA SH. GALADIMA)',598],
				['PRIMARY SCHOOL MAKARANTA, TUNGAR MADUGU (MAKARANTA TUNGAR MADUGU)',587],
				['OPPOSITE ISLAMIYYA, OPEN SPACE (MAKARANTA TUNGAR KWANGI)',490],
				['TREE SHADE, OPEN SPACE DANFILI, RUMBUJE (DAN FILI RUMBUJE)',704],
				['PRIMARY SCHOOL MAKARANTA/T/TUDU BUGA (MAKARANTA T/TUDU BUGA)',573],
				['PRIMARY SCHOOL MAKARANTA /RANGANDAWA (MAKRANTA/ RANGANDAWA)',461],
				['UNDER TREE SHADE ,NEAR MOSQUE DANFILI, AGAJIBA (DAN FILI AGAJIBA)',314],
				['PRIMARY SCHOOL MAKARANTA, KARANBI (MAKARANTA KARANBI)',817],
				['CLOSE TO WELL, OPEN SPACE KWAREN GEZU (DAN FILI KWAREN GEZU)',231],
				['UNDER TREE SHADE, OPEN SPACE GIDAN ALFARMA, DAKWALE MAYEL (GIDAN ALFARMA DAKWALLE, MAYEL)',635],
				['PRIMARY SCHOOL TUNGAR RAFI (SHIYAR HAKIMI, TUNGAR RAFI)',274],
				['PRIMARY SCHOOL TUNGAR KURFAI (DANFILI, TUNGAR KURFAI)',279],
				['TSAKAR GARI, TUNGAR KWANGI',284],
				['T/KWACI‐DAN FILI',326]
			];
		}
	}