<?php
namespace App\Services\PollingUnit\Gwadabawa;
	
	class Gwadabawa
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				['TSOHOWAR MAGINA, SH. GALADIMA/MULLELA',993],
				['TSOHOWAR MAGINA, SHIYAR GALADIMA MULLELA I',1099],
				['TSOHOWAR MAGINA, SHIYAR GALADIMA MULLELA II',643],
				['YAN ALEWA BAYAN GIDAN ALTU,',939],
				['YAN ALEWA BAYAN GIDAN BELLO',731],
				['TAMBARI M.P.S, SHIYAR TAWAYAWA I',764],
				['TAMBARI M.P.S, SHIYAR TAWAYAWA II',806],
				['TAMBARI M.P.S, SHIYAR TAWAYAWA III',980],
				['MAITURARE M.P.S, SH. MAGAJI ALJANA',735],
				['MAITURARE M.P.S, SH. MAGAJI D/JANA',464],
				['N.O.A OFFICE, SH TUDU/DANZARAWA',874],
				['SHIYAR DAN ZAKARA, SHIYAR TUDU/ DAN ZAKARA',723],
				['J.S.S GWADABAWA, SH. S. FAWA I',621],
				['J.S.S GWADABAWA, SH. S. FAWA II',944],
				['SHIYAR SARKIN YAKI RANGANDA)',658],
				['TSOLAWO, TSOLAWO',540],
				['GAWO GWANBILLA',307],
				['PRY SCH, ABDALO',618],
				['TSAKAR GARI, TUDUN DOKI',931],
				['OLD PRI. SCH. GIDAN IDALTU',598],
				['HOSPITAL, CHANCHA',582],
				['PRY SCH, CHANCHA',632],
				['TSAKAR GARI TAKARAWA',392],
				['TSOHUWAR MAGINA KAIBUN ATIKU',493],
				['SHIYAR MAKERA RANGANDA', 516],
				['BAYAN GIDAN ALTU, SHIYAR YANALEWA',482],
				['TAMBARI M.P.S, SHIYAR TAWAYAWA',559],
				['MAITURARE M.P.S, DAN ALJANNA',455]
			];
		}
	}