<?php
namespace App\Services\PollingUnit\Bodinga;
	
	class MazanGari
	{
		
		function __construct()
		{
			# code...
			 $this->pollingUnits = $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				// 'PRY SCH, KAURA MIWYO',
				// 'S/HAKIMI D/BABARBARE (SHIYAR HAKIMI, DAN BABARBARE)',
				// 'PRY SCH, TANDARAWA',
				// 'SHIYAR HAKIMI, KIMBA KAURARE',
				// 'HURUMI PRY SCH, HURUMI',
				// 'SHIYAR MAGAJI, KABAWA',
				// 'ADULT EDUCATION SHIYAR MAGAJI, JIRGA (S/MAGAJI JIRGA)',
				// 'DISPENSARY SHIYAR FULANI, JIRGA (S/FULANI JIRGA)',
				// 'SHIYAR MAGAJI, SIRE MAIGISHIRI',
				// 'MAKARANTA (S/MAGAJI, SIRE KAKA)',
				// 'PRY SCH, DAN NARBA',
				// 'SHIYAR HAKIMI, TUDUN MANU',
				// 'FANFO SH.MAGAJI, TUDUN NUFAWA',
				// 'SHIYAR MAGAJI, RUMBU',
				// 'SHIYAR HARIMI, KAURA IYARA',
				// 'DISPENSARY SHIYAR KAURARE, MAZAN GARI (S/KAURARE MAZAN GARI)',
				// 'PRY SCH, GWARKO',
				// 'PRY SCH, BUTURU',
				// 'PRY SCH, RUGA GADO',
				// 'SHIYAR HAKIMI, KULODO',
				// 'KAURAMIYO ADULT EDUCATION KAURAMIYO',
				// 'ABDUL SALAMU KAURAMIYO'

				['PRY SCH, KAURA MIWYO', 785],
				['SHIYAR HAKIMI, DAN BABARBARE', 279],
				['PRY SCH, TANDARAWA', 335],
				['SHIYAR HAKIMI, KIMBA KAURARE', 478],
				['HURUMI PRY SCH, HURUMI', 446],
				['SHIYAR MAGAJI, KABAWA', 448],
				['SHIYAR MAGAJI, JIRGA', 357],
				['SHIYAR FULANI, JIRGA', 551],
				['SHIYAR MAGAJI, SIRE MAIGISHIRI', 443],
				['SHIYAR MAGAJI, SIRE KAKA', 483],
				['PRY SCH, DAN NARBA', 579],
				['SHIYAR HAKIMI, TUDUN MANU', 510],
				['FANFO SH.MAGAJI, TUDUN NUFAWA', 403],
				['SHIYAR MAGAJI, RUMBU', 341],
				['SHIYAR HARIMI, KAURA IYARA', 212],
				['SHIYAR KAURARE, MAZAN GARI', 488],
				['PRY SCH, GWARKO', 454],
				['PRY SCH, BUTURU', 425],
				['PRY SCH, RUGA GADO', 410],
				['SHIYAR HAKIMI, KULODO', 294],
				['KAURAMIYO ADULT EDUCATION KAURAMIYO', 683],
				['ABDUL SALAMU KAURAMIYO', 372]
			];
		}
	}