<?php
namespace App\Services\PollingUnit\Bodinga;
	
	class Sifawa
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				// 'PRY SCH, SHIYAR KUDU I',
				// 'PRY SCH, SHIYAR KUDU II',
				// 'SHIYAR HAKIMI, SHIYAR KUDU',
				// "JAM'ATU NASARAL ISLAM, SHIYAR AREWA",
				// 'ADULT ED NASARAL ISLAM, SHIYAR AREWA',
				// 'COURT AREA , SHIYAR AREWA',
				// 'PRY SCH, ABDULSALAMI',
				// 'PRI. SCH LOZOBE/DABAGI',
				// 'GIDAN RUGGA, SHIYAR YAMMA I',
				// 'SHIYAR HAKIMI, ABDULSALAMI II',
				// 'SHIYAR HAKIMI, ABDULSALAMI',
				// 'SHIYAR HAKIMI, GIDAN ABBA',
				// 'SHIYAR HAKIMI, HARUMI/FADAMA/ HURUMI FADAMA SH/HAKIMI',
				// 'PRY SCH, LURUYAWA',
				// 'SHIYAR MAIDABO, GIDAN SAMI',
				// 'SHIYAR HAKIMI, YARAREWA'

				['PRY SCH, SHIYAR KUDU I', 921],
				['PRY SCH, SHIYAR KUDU II', 739],
				['PRY SCH, TANDARAWASHIYAR HAKIMI, SHIYAR KUDU', 777],
				["JAM'ATU NASARAL ISLAM, SHIYAR AREWA", 1,322],
				['ADULT ED NASARAL ISLAM, SHIYAR AREWA', 743],
				['COURT AREA , SHIYAR AREWA', 1,026],
				['PRY SCH, ABDULSALAMI', 395],
				['PRI. SCH LOZOBE/DABAGI', 369],
				['GIDAN RUGGA, SHIYAR YAMMA I', 811],
				['SHIYAR HAKIMI, ABDULSALAMI II', 558],
				['SHIYAR HAKIMI, ABDULSALAMI', 444],
				['SHIYAR HAKIMI, GIDAN ABBA', 359],
				['SHIYAR HAKIMI, HARUMI/FADAMA/ HURUMI FADAMA SH/HAKIMI', 632],
				['PRY SCH, LURUYAWA', 561],
				['SHIYAR MAIDABO, GIDAN SAMI', 278],
				['SHIYAR HAKIMI, YARAREWA', 276]
			];
		}
	}