<?php
namespace App\Services\PollingUnit\Bodinga;
	
	class Tulluwa
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				// 'DISPENSARY, TULLAWA',
				// 'SHIYAR KAKIMI, RUGGAR YANTU',
				// 'SHIYAR KAKIMI, RUGGAR JATAU I',
				// 'SHIYAR KAKIMI, RUGGAR JATAU II',
				// 'SHIYAR KAKIMI, GYASHARU',
				// 'DISPENSARY GIDAN TSARA (S/KAKIMI,GIDAN TSARA)',
				// 'PRY SCH, GIDAN TSARA',
				// 'PRY SCH. GIDAN RUWA (S/HAKIMI GIDAN RUWA)',
				// 'PRY SCH, BAGARUNNE',
				// 'PRY. SCH. KWALFA (HAYAN GIDANS/HAUMI KWALFA I)',
				// 'SHIYAR HAKIMI, KWALFA II',
				// 'DISPENSARY KULAFASA (S/HAKIMI KULAFASA I)',
				// 'SHIYAR HAKIMI, KULAFASA II',
				// 'PRY SCH, HAUSAWA',
				// 'DANFILI ALASAWA (SHIYAR HAKIMI HAUSAWA)',
				// 'SHIYAR HAKIMI, SAIDAWA',
				// 'PRY SCH, TULLUWA'

				['DISPENSARY, TULLAWA', 324],
				['SHIYAR KAKIMI, RUGGAR YANTU', 353],
				['SHIYAR KAKIMI, RUGGAR JATAU I', 304],
				['SHIYAR KAKIMI, RUGGAR JATAU II', 282],
				['SHIYAR KAKIMI, GYASHARU', 278],
				['SHIYAR KAKIMI, GIDAN TSARA', 546],
				['PRY SCH, GIDAN TSARA', 594],
				['SHIYAR HAKIMI, GIDAN RUWA', 499],
				['PRY SCH, BAGARUNNE', 582],
				['SHIYAR HAUMI, KWALFA I', 612],
				['SHIYAR HAKIMI, KWALFA II', 564],
				['SHIYAR HAKIMI, KULAFASA I', 365],
				['SHIYAR HAKIMI, KULAFASA II', 386],
				['PRY SCH, HAUSAWA', 396],
				['SHIYAR HAKIMI, HAUSAWA', 302],
				['SHIYAR HAKIMI, SAIDAWA', 321],
				['PRY SCH, TULLUWA', 341]
			];
		}
	}