<?php
namespace App\Services\PollingUnit\DangeShuni;
	
	class Dange
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				// 'S/BAURA NIZZAMIYA/KANWURI',
				// 'BUIDE BAKIN TITI/PRIMARY SCHOOL KANWURI (BAKIN TITI) (BUIDE BAKIN TITI)',
				// 'ADARAWA/GINDIN ITACEN LIM OPP. GIDAN ABDULLAHI MAI BUHU (ADARAWA)',
				// 'BAKIN KASUWA',
				// 'PRIMARY SCHOOL MALLAMAWA (GARKAR NABOKOMALLAMAWA)',
				// 'TAKALMAWA,BAKIN FANFO',
				// 'TAKALMAWA 2/MODEL PRIMARY SCHOOL BAKIN KASUWA (TAKALMAWA)',
				// 'PRY SCH, KINDIRU',
				// 'PRY SCH, HAUSAWA',
				// 'FILIN BALILA TUSHEN LIM (HAUSAGARKAN HAKIMI)',
				// 'MODEL PRY SCH, DANKILO',
				// 'MODEL PRY SCH, GIDAN AJIYA',
				// 'MODEL PRY SCH, RUNJI',
				// 'BANGON GIDAN MALAM CHIKA TUKANAWA (GARKAR MALAM MAIDAMA)',
				// 'DARKANA/TUSHEN ITACEN LIM KUSA DA KOFA ALH. ALTINE (GARKAR NAGAKE DAKARNA)',
				// 'DAFILIN KAURARE MASALLACI',
				// 'BAKIN KASUWA‐BUIDE'

				['S/BAURA NIZZAMIYA/KANWURI', 1,014],
				['BUIDE BAKIN TITI', 722],
				['ADARAWA, ADARAWA', 675],
				['BAKIN KASUWA', 761],
				['GARKAR NABOKO, MALLAMMAWA', 499],
				['TAKALMAWA,BAKIN FANFO', 860],
				['TAKALMAWA, TAKALMAWA', 415],
				['PRY SCH, KINDIRU', 740],
				['PRY SCH, HAUSAWA', 574],
				['HAUSA GARKAR HAKIMI', 528],
				['MODEL PRY SCH, DANKILO', 573],
				['MODEL PRY SCH, GIDAN AJIYA', 567],
				['MODEL PRY SCH, RUNJI', 1,263],
				['GARKAR MALAM MAIDAMA', 569],
				['GARKAR NAGAKE, DARKANA', 942],
				['DAFILIN KAURARE MASALLACI', 398],
				['BAKIN KASUWA - BUIDE', 865]
				
			];
		}
	}