<?php
namespace App\Services\PollingUnit\Illela;
	
	class Darna
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				// 'DARNA SABON GARI, SHIYAR GALADIMA',
				// 'GIDAN TUDU, MAKARANTA',
				// 'TUNGAR ZANGO, MAKARANTA',
				// 'DARNA KILIYA, MAKARANTA',
				// 'TSIRA RAI, G./SALE',
				// 'HARAGAWA, MAKARANTA',
				// 'UNDER A TREE MULLELA (MULLELA)',
				// 'TUNGAR MATSI, S/SALAU',
				// 'UNDER A TREE GIDAN KWARE (GIDAN KWARE S/HAKIMI)',
				// 'UNDER A TREE TUNGAL DIYA (YUNGAR DIYA S/HAKIMI)',
				// 'DARNA KWANGO, S. HAKIMI',
				// 'GIDAN RABO, SHIYAR MAGAJI',
				// 'MAIMASU, MAIMASU',
				// 'GALADIMA GIDAN SALAU, SHIYAR HAKIMI',
				// 'GIDAN GWANYO, SHIYAR HAKIMI',
				// 'TUNGAR ZANGO, TUNGAR ZANGO'

				['DARNA SABON GARI, SHIYAR GALADIMA', 1,108],
				['GIDAN TUDU, MAKARANTA',1,110],
				['TUNGAR ZANGO, MAKARANTA', 564],
				['DARNA KILIYA, MAKARANTA', 1085],
				['TSIRA RAI, G./SALE', 445],
				['HARAGAWA, MAKARANTA', 725],
				['MULLELA, MULLELA', 329],
				['TUNGAR MATSI, S/SALAU', 441],
				['GIDAN KWARE, S. HAKIMI',424],
				['TUNGAL DIYA, S. HAKIMI', 490],
				['DARNA KWANGO, S. HAKIMI', 402],
				['GGIDAN RABO, SHIYAR MAGAJI', 490],
				['MAIMASU, MAIMASU',215],
				['GALADIMA GIDAN SALAU, SHIYAR HAKIMI',509],
				['GIDAN GWANYO, SHIYAR HAKIMI',207],
				['TUNGAR ZANGO, TUNGAR ZANGO', 527]
			];
		}
	}