<?php
namespace App\Services\PollingUnit\Illela;
	
	class GHamma
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				// 'GIDAN IDDAU',
				// 'SHIYAR ADARAWA, HILIN INWALA',
				// 'MUNWADATA, MUNWADATA',
				// 'SHIYAR ABDULRAZIKU, DAN HILI',
				// 'TUNGAR ALMU, T/ALMU',
				// 'ZANGON SHAHO, ZANGON SHAHO',
				// 'MANSALAWA BABBA',
				// 'DARAMBA',
				// 'SHIYAR GARBA, HAKIMI',
				// 'TAKALMAWA, TAKALMAWA',
				// 'TAKA TSABA',
				// 'TSANGALADAM, TSANGALADAM',
				// 'GIDAN MAKERA',
				// 'GIDAN MAKERA, SH MAGAJI MAKARANTA',
				// 'SHIYAR MAGAJI, MAKARANTA',
				// 'GIDAN ABUBA, GIDAN ABUBA',
				// 'SHIYAR RAFI',
				// 'AMBARURA Y/ MASALAWA, Y/AMBARURA',
				// 'AMBARURA DABAGI, S. LATSA',
				// 'GIDAN FAJA, GIDAN FAJA',
				// 'HERE, HERE',
				// 'HURA GIRKE, HURA GIRKE',
				// 'DUMAJE KWARE',
				// 'AMBARURA MAKARANTA, MAKARANTA',
				// 'AMBARURA INWALA, MAKARANTA',
				// 'SHIYAR RAFI B, S/RAFI',
				// 'AMBARURAWA DAN HILI MAKARANTA',
				// 'AMBARURA MAKARANTA B, DANHILI'
				
				['GIDAN IDDAU', 302],
				['SHIYAR ADARAWA, HILIN INWALA',292],
				['MUNWADATA, MUNWADATA', 292],
				['SHIYAR ABDULRAZIKU, DAN HILI', 243],
				['TUNGAR ALMU, T/ALMU', 508],
				['ZANGON SHAHO, ZANGON SHAHO', 505],
				['MANSALAWA BABBA', 382],
				['DARAMBA', 724],
				['SHIYAR GARBA, HAKIMI',477],
				['TAKALMAWA, TAKALMAWA', 402],
				['TAKA TSABA', 434],
				['TSANGALADAM, TSANGALADAM', 397],
				['GIDAN MAKERA', 158],
				['GIDAN MAKERA, SH MAGAJI MAKARANTA', 365],
				['SHIYAR MAGAJI, MAKARANTA', 1,014],
				['GIDAN ABUBA, GIDAN ABUBA', 413],
				['SHIYAR RAFI', 317],
				['AMBARURA Y/ MASALAWA, Y/AMBARURA', 323],
				['AMBARURA DABAGI, S. LATSA', 356],
				['GIDAN FAJA, GIDAN FAJA', 229],
				['HERE, HERE', 374],
				['HURA GIRKE, HURA GIRKE', 427],
				['DUMAJE KWARE',973],
				['AMBARURA MAKARANTA, MAKARANTA', 535],
				['AMBARURA INWALA, MAKARANTA', 420],
				['SHIYAR RAFI B, S/RAFI',307],
				['AMBARURAWA DAN HILI MAKARANTA', 524],
				['AMBARURA MAKARANTA B, DANHILI', 507]
			];
		}
	}