<?php
namespace App\Services\PollingUnit\Illela;
	
	class Illela
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				// 'SHIYAR BAWA II TSOHUWARKOTU',
				// 'SHIYAR LIHODA SONANI',
				// 'SHIYAR BAWA MAKARANTA',
				// 'SHIYAR UBANDA WAKI / KAWURU',
				// 'TSOHUWAR TASHA S/TUDUN AMARWA',
				// 'SHIYAR TUDU MAKARANTA',
				// 'A M PRI. SCH. (FILIN HAMZA SHIYAR NAMATA)',
				// 'SHIYAR NAMATA SHIYAR MAIUNGUWA',
				// 'SHIYAR MAMATA',
				// 'TUDUN GUDALEKWA / KWARA',
				// 'SHIYAR UBANDAWAKI G/TANKO MAIHIRDE',
				// 'SHIYAR BAWA III G/KIFI',
				// 'SHIYAR MAIDAWA II, GIDAN DANLIYOSO',
				// 'SHIYAR BAWA / FILI DAN WAZAM',
				// 'TUDUN GUDALE MAIRUWA I',
				// 'TUDUN GUDALE MAIRUWA II',
				// 'SHIYAR NAMATA',
				// 'GIDAN KYASU, GIDAN KYASU',
				// 'SH/UBANDAWAKI / G/YARMA',
				// 'SH / BAWA MAKARANTA',
				// 'SHIYAR BAWA, V. ABIYARIMA',
				// 'SH/NAMATA G.G.S.S',
				// 'SHIYAR NAMATA, HILIN NAMATA/SH/MADAWA ISNOMAU',
				// 'NIGERIA NIGER MARKET (SHIYAR BAWA GIDAN S/SHANU)',
				// 'SH/LIHIDDA MAKARANTA SONANE',
				// 'SH/SABON GARI AMARAWA GAWO'

				['SHIYAR BAWA II TSOHUWARKOTU', 1,378],
				['SHIYAR LIHODA SONANI',1,017],
				['SHIYAR BAWA MAKARANTA', 1,266],
				['SHIYAR UBANDA WAKI / KAWURU', 1081],
				['TSOHUWAR TASHA S/TUDUN AMARWA', 1,181],
				['SHIYAR TUDU MAKARANTA', 1,107],
				['FILIN HAMZA SHIYAR NAMATA', 1,280],
				['SHIYAR NAMATA SHIYAR MAIUNGUWA', 812],
				['SHIYAR MAMATA',1,292],
				['TUDUN GUDALEKWA / KWARA', 744],
				['SHIYAR UBANDAWAKI G/TANKO MAIHIRDE', 1,153],
				['SHIYAR BAWA III G/KIFI', 848],
				['SHIYAR MAIDAWA II, GIDAN DANLIYOSO', 1096],
				['SHIYAR BAWA / FILI DAN WAZAM', 929],
				['TUDUN GUDALE MAIRUWA I', 417],
				['TUDUN GUDALE MAIRUWA II',608],
				['SHIYAR NAMATA', 1,108],
				['GIDAN KYASU, GIDAN KYASU', 298],
				['SH/UBANDAWAKI / G/YARMA', 1087],
				['SH / BAWA MAKARANTA', 786],
				['SHIYAR BAWA, V. ABIYARIMA', 1,140],
				['SH/NAMATA G.G.S.S', 973],
				['SHIYAR NAMATA, HILIN NAMATA/SH/MADAWA ISNOMAU', 2,408],
				['SHIYAR BAWA GIDAN S/SHANU', 1,397],
				['SH/LIHIDDA MAKARANTA SONANE', 957],
				['SH/SABON GARI AMARAWA GAWO', 733]
			];
		}
	}