<?php
namespace App\Services\PollingUnit\Illela;
	
	class Kalmalo
	{
		
		function __construct()
		{
			# code...
			$this->pollingUnits =  $this->pollingUnits();
		}

		public function pollingUnits(){
			return [
				// 'SHIYAR GALADIMA, ASIBITI',
				// 'UNDER A TREE S/MAMMAN ALA (SHIYAR GALADIMA S. MAMMAN ALA)',
				// 'UNDER A TREE S/WADATA (SHIYAR RAFI S/WADATA)',
				// 'UNDER A TREE SHIYAR AJIYA (SHIYAR AJIYA, S. AJIYA)',
				// 'RUNDJIN KUWARE, MAKARANTA',
				// 'JEMA, S/MAGAJI',
				// 'TUMBULUNKUM, BABBAN HILI',
				// 'MUNWADATA, MAKARANTA',
				// 'RUNJINTUDU, MAKARANTA',
				// 'SABON GARI MAKARANTA',
				// 'UNDER A TREE TABKIN TARAMNIYA (TAFKIN TARAMNIYA S/ALFAMMA)',
				// 'UNDER A TREE S/KALMALO (SHIYAR DAN GALADIMA S/KELUATO)'

				['SHIYAR GALADIMA, ASIBITI', 827],
				['SHIYAR GALADIMA, S/MAMMAN ALA',521],
				['SHIYAR RAFI, S/WADATA', 700],
				['SHIYAR AJIYA, S/AJIYA', 617],
				['RUNDJIN KUWARE, MAKARANTA', 588],
				['JEMA, S/MAGAJI', 592],
				['TUMBULUNKUM, BABBAN HILI', 479],
				['MUNWADATA, MAKARANTA', 652],
				['RUNJINTUDU, MAKARANTA',576],
				['SABON GARI MAKARANTA', 946],
				['TABKIN TARAMNIYA, S/ALFARMA', 347],
				['SHIYAR DANGALADIMA, S/KALMALO', 530]
			];
		}
	}